export type Bindings = {
  ANTHROPIC_API_KEY: string;
  TMDB_ACCESS_TOKEN: string;
};

export interface Movie {
  id: number;
  title: string;
  year: number;
  posterPath: string;
  originalLanguage: string;
  genres: string[];
}

/**
 * generated by AI
 */
export interface AIRecommendation {
  title: string;
  year: number;
  reason: string;
  matchPercentage: number;
}

/**
 * response for frontend
 * combined TMDB data + AI
 */
export interface Recommendation {
  id: number;
  title: string;
  year: number;
  posterPath: string;
  genres: string[];
  reason: string;
  matchPercentage: number;
  trailerKey: string;
}
